#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get -y update && sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \$hostname;/" /etc/nginx/nginx.conf
sudo service nginx start
