#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
sudo apt-get -y update && sudo apt-get -y install haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 235025-web-01 52.91.135.32:80 check\n\tserver 235025-web-02 54.87.238.32:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
