#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
apt-get -y update && apt-get -y install haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 235025-web-01  52.91.135.32:80 check\n\tserver 235025-web-02 54.87.238.32:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
