#!/bin/bash
# install and add rules to ufw
apt-get update && apt-get install -y ufw
echo y | sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
